In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ptl
import scipy.optimize as opt
from sklearn import preprocessing

In [4]:
df=pd.read_csv("ChurnData.csv")
df.head(9)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6    42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7     9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8    35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   
5    20.70  ...      0.0       0.0       0.0     0.0    0.0    3.030    3.240   
6     8.25  ...      0.0       1.0       1.0     1.0    1.0    2.110    3.157   
7     2.90  ...      0.0       0.0       0.0     0.0    0.0    1.065    3.240   
8     6.50  ...      0.0       0.0       1.0     1.0    0.0    1.872    3.314   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  
5  4.787      1.0    0.0  
6  3.611      4.0    0.0  
7  2.833      1.0    0.0  
8  4.942      3.0    0.0  

[9 rows x 28 columns]

In [5]:
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [6]:
churn_df=df[['tenure', 'age', 'address', 'income','ed', 'employ', 'equip','callcard', 'wireless','churn']]
churn_df[['churn']]=churn_df[['churn']].astype(int)
churn_df.head(9)

F:\Installed Softwares\Anaconda\lib\site-packages\pandas\core\frame.py:3137: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0   
6    42.0  40.0      7.0    37.0  2.0     8.0    1.0       1.0       1.0   
7     9.0  21.0      1.0    17.0  2.0     2.0    0.0       0.0       0.0   
8    35.0  50.0     26.0   140.0  2.0    21.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0

In [9]:
X=np.asarray(churn_df[['tenure', 'age', 'address', 'income','ed', 'employ', 'equip','callcard', 'wireless']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.]])

In [11]:
Y=np.asarray(churn_df[['churn']])
Y[0:5]

array([[1],
       [1],
       [0],
       [0],
       [0]])

In [12]:
X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148]])

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=10,test_size=0.2)

In [33]:
print("X :",X_train.shape,X_test.shape)
print("Y :",Y_train.shape,Y_test.shape)

X : (160, 9) (40, 9)
Y : (160, 1) (40, 1)


In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

In [35]:
LR= LogisticRegression(C=0.01,solver='liblinear').fit(X_train,Y_train)
LR

F:\Installed Softwares\Anaconda\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
yhat=LR.predict(X_test)
yhat

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [37]:
yhat_prob=LR.predict_proba(X_test)
yhat_prob

array([[0.40026366, 0.59973634],
       [0.74155956, 0.25844044],
       [0.67750248, 0.32249752],
       [0.49891671, 0.50108329],
       [0.54679829, 0.45320171],
       [0.5858823 , 0.4141177 ],
       [0.54297985, 0.45702015],
       [0.44490915, 0.55509085],
       [0.71820774, 0.28179226],
       [0.55015621, 0.44984379],
       [0.71389204, 0.28610796],
       [0.69843625, 0.30156375],
       [0.59308108, 0.40691892],
       [0.56603304, 0.43396696],
       [0.70503362, 0.29496638],
       [0.59002803, 0.40997197],
       [0.58884609, 0.41115391],
       [0.71124694, 0.28875306],
       [0.62127842, 0.37872158],
       [0.48928742, 0.51071258],
       [0.76184994, 0.23815006],
       [0.81220079, 0.18779921],
       [0.53415756, 0.46584244],
       [0.64504381, 0.35495619],
       [0.52619581, 0.47380419],
       [0.41274104, 0.58725896],
       [0.44116795, 0.55883205],
       [0.54264905, 0.45735095],
       [0.51388681, 0.48611319],
       [0.44377678, 0.55622322],
       [0.

In [40]:
from sklearn.metrics import jaccard_similarity_score,classification_report
print(jaccard_similarity_score(Y_test,yhat))

0.775


F:\Installed Softwares\Anaconda\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


In [41]:
print(confusion_matrix(Y_test,yhat,labels=[0,1]))

[[23  3]
 [ 6  8]]


In [42]:
print(classification_report(Y_test,yhat))

              precision    recall  f1-score   support

           0       0.79      0.88      0.84        26
           1       0.73      0.57      0.64        14

    accuracy                           0.78        40
   macro avg       0.76      0.73      0.74        40
weighted avg       0.77      0.78      0.77        40



In [44]:
from sklearn.metrics import log_loss
print(log_loss(Y_test,yhat_prob))

0.5752198113105205
